/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClientSideFormSubmitRouteRouteImport } from './routes/client-side-form-submit/route'
import { Route as ActivityTestRouteRouteImport } from './routes/activity-test/route'
import { Route as IndexRouteImport } from './routes/index'

const ClientSideFormSubmitRouteRoute =
  ClientSideFormSubmitRouteRouteImport.update({
    id: '/client-side-form-submit',
    path: '/client-side-form-submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActivityTestRouteRoute = ActivityTestRouteRouteImport.update({
  id: '/activity-test',
  path: '/activity-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-test': typeof ActivityTestRouteRoute
  '/client-side-form-submit': typeof ClientSideFormSubmitRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-test': typeof ActivityTestRouteRoute
  '/client-side-form-submit': typeof ClientSideFormSubmitRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-test': typeof ActivityTestRouteRoute
  '/client-side-form-submit': typeof ClientSideFormSubmitRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activity-test' | '/client-side-form-submit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activity-test' | '/client-side-form-submit'
  id: '__root__' | '/' | '/activity-test' | '/client-side-form-submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityTestRouteRoute: typeof ActivityTestRouteRoute
  ClientSideFormSubmitRouteRoute: typeof ClientSideFormSubmitRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/client-side-form-submit': {
      id: '/client-side-form-submit'
      path: '/client-side-form-submit'
      fullPath: '/client-side-form-submit'
      preLoaderRoute: typeof ClientSideFormSubmitRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-test': {
      id: '/activity-test'
      path: '/activity-test'
      fullPath: '/activity-test'
      preLoaderRoute: typeof ActivityTestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityTestRouteRoute: ActivityTestRouteRoute,
  ClientSideFormSubmitRouteRoute: ClientSideFormSubmitRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
