/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ClientSideFormSubmitRouteImport } from './routes/client-side-form-submit/route'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ClientSideFormSubmitRouteRoute = ClientSideFormSubmitRouteImport.update({
  id: '/client-side-form-submit',
  path: '/client-side-form-submit',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/client-side-form-submit': {
      id: '/client-side-form-submit'
      path: '/client-side-form-submit'
      fullPath: '/client-side-form-submit'
      preLoaderRoute: typeof ClientSideFormSubmitRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client-side-form-submit': typeof ClientSideFormSubmitRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client-side-form-submit': typeof ClientSideFormSubmitRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/client-side-form-submit': typeof ClientSideFormSubmitRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/client-side-form-submit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/client-side-form-submit'
  id: '__root__' | '/' | '/client-side-form-submit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientSideFormSubmitRouteRoute: typeof ClientSideFormSubmitRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientSideFormSubmitRouteRoute: ClientSideFormSubmitRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/client-side-form-submit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/client-side-form-submit": {
      "filePath": "client-side-form-submit/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
